--- #YAML:1.0
name:               Parallel-Queue
version:            2.02
abstract:           fork list of subref's N-way parallel
author:
    - Steven Lembark <lembark@wrkhors.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:    0
    Config:  0
    strict:  0
    Symbol:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
