---
abstract: "fork list of subref's N-way parallel"
author:
  - 'Steven Lembark <lembark@wrkhors.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Parallel-Queue
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Scalar::Util: 0
  Symbol: 0
  strict: 0
version: 3.00
