# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Parallel-Queue
version:      1.00
version_from: 
installdirs:  site
requires:
    Carp:                          0
    Config:                        0
    strict:                        0
    Symbol:                        0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
